# Generated by Django 4.2 on 2023-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Stuff-Acceleration', 'Stuff Acceleration'), ('Stuff-Direction', 'Stuff Direction'), ('Admin', 'Admin')], default='Standard', max_length=150),
        ),
    ]
