# Generated by Django 4.2 on 2023-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customusermodel_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="cv",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
