# Generated by Django 4.2 on 2023-04-27 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccelerationProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("requirements", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("program_start_time", models.DateField()),
                ("program_end_time", models.DateField()),
                ("registration_start_date", models.DateField()),
                ("registration_end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("directions", models.ManyToManyField(to="directions.direction")),
            ],
        ),
        migrations.CreateModel(
            name="ApplicantResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_response_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=150,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Applicants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=150,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="StuffResponseDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Accepted", "Accepted"),
                            ("Maybe", "Maybe"),
                            ("Rejected", "Rejected"),
                        ],
                        default="None",
                        max_length=150,
                    ),
                ),
                (
                    "applicant_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.applicantresponse",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="acceleration_program.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoinProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_applicants", models.IntegerField(default=0)),
                (
                    "applicants",
                    models.ManyToManyField(
                        through="acceleration_program.Applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directions.direction",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.accelerationprogram",
                    ),
                ),
                (
                    "stages_data",
                    models.ManyToManyField(to="acceleration_program.stage"),
                ),
            ],
            options={
                "unique_together": {("direction", "program")},
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="acceleration_program.assignmenttype",
            ),
        ),
        migrations.AddField(
            model_name="applicants",
            name="program_to_join",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_applicant",
                to="acceleration_program.joinprogram",
            ),
        ),
        migrations.AddField(
            model_name="applicantresponse",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="acceleration_program.stage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicants",
            unique_together={("program_to_join", "applicant")},
        ),
        migrations.AlterUniqueTogether(
            name="applicantresponse",
            unique_together={("applicant", "stage")},
        ),
    ]
