# Generated by Django 4.2 on 2023-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccelerationProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("requirements", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("program_start_time", models.DateField()),
                ("program_end_time", models.DateField()),
                ("registration_end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("directions", models.ManyToManyField(to="directions.direction")),
            ],
        ),
    ]
