# Generated by Django 4.2 on 2023-04-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("directions", "0001_initial"),
        ("acceleration_program", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantresponse",
            name="direction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="directions.direction",
            ),
            preserve_default=False,
        ),
    ]
