# Generated by Django 4.2 on 2023-04-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("directions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acceleration_program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_response_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=150,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Applicants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=150,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoinProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_applicants", models.IntegerField()),
                (
                    "applicants",
                    models.ManyToManyField(
                        blank=True,
                        through="acceleration_program.Applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directions.direction",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.accelerationprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Test", "Test"),
                            ("Task", "Task"),
                            ("Live Coding", "Live Coding"),
                            ("Interview", "Interview"),
                        ],
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StuffResponseDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Accepted", "Accepted"),
                            ("Maybe", "Maybe"),
                            ("Rejected", "Rejected"),
                        ],
                        default="None",
                        max_length=150,
                    ),
                ),
                (
                    "applicant_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.applicantresponse",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("assigment_with_description", models.TextField()),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directions.direction",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="acceleration_program.stagetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderedStages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_number", models.PositiveIntegerField()),
                (
                    "join_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.joinprogram",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.stage",
                    ),
                ),
            ],
            options={
                "unique_together": {("join_program", "stage")},
            },
        ),
        migrations.AddField(
            model_name="joinprogram",
            name="stages_data",
            field=models.ManyToManyField(
                through="acceleration_program.OrderedStages",
                to="acceleration_program.stage",
            ),
        ),
        migrations.AddField(
            model_name="applicants",
            name="program_to_join",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_applicant",
                to="acceleration_program.joinprogram",
            ),
        ),
        migrations.AddField(
            model_name="applicantresponse",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="acceleration_program.stage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="joinprogram",
            unique_together={("direction", "program")},
        ),
        migrations.AlterUniqueTogether(
            name="applicantresponse",
            unique_together={("applicant", "stage")},
        ),
    ]
