# Generated by Django 4.2 on 2023-05-05 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acceleration_program", "0002_applicantresponse_direction"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stuffresponsedescription",
            unique_together={("author", "applicant_response")},
        ),
    ]
