# Generated by Django 4.2 on 2023-04-24 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acceleration_program", "0003_accelerationprogram_registration_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinprogram",
            name="applicants",
            field=models.ManyToManyField(
                through="acceleration_program.Applicants", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="joinprogram",
            name="joined_applicants",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
