# Generated by Django 4.2 on 2023-05-14 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "acceleration_program",
            "0005_rename_program_end_time_accelerationprogram_program_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StuffResponseDescription",
            new_name="StuffFinalResponseDescription",
        ),
    ]
