# Generated by Django 4.2 on 2023-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acceleration_program", "0006_alter_stagetype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinprogram",
            name="joined_applicants",
            field=models.IntegerField(default=0),
        ),
    ]
