# Generated by Django 4.2 on 2023-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "acceleration_program",
            "0006_rename_stuffresponsedescription_stufffinalresponsedescription",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stufffinalresponsedescription",
            name="status",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                max_length=150,
            ),
        ),
    ]
