# Generated by Django 4.2 on 2023-05-14 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("acceleration_program", "0007_alter_stufffinalresponsedescription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StuffMembersResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.FloatField()),
                (
                    "applicant_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceleration_program.applicantresponse",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("author", "applicant_response")},
            },
        ),
    ]
